"""SBOL 3 facility catalogs, material custody, and run provenance."""

from . import namespaces as _namespaces
from .document import (
    add_all,
    configure_namespace,
    configure_synbiohub,
    make_document,
    read_document,
    write_document,
    write_rdfxml,
    write_turtle,
)
from .factories import (
    add_child,
    discard,
    discard_implementation,
    grid_positions,
    locate,
    make_asset,
    make_bacterial_stock,
    make_box,
    make_capability,
    make_diluted_plasmid,
    make_facility,
    make_fridge_4c,
    make_fridge_minus20,
    make_fridge_minus80,
    make_material_lot,
    make_plated_strain,
    make_procured_material,
    make_property,
    make_shelf,
    make_single_well_petri_dish_plate,
    make_solid_96_well_plate,
    make_solid_media_plate,
    make_square_96_position_plate,
    make_zone,
    move_item,
    place_in_container,
    place_in_plate,
    place_item,
    remove_from_container,
)
from .provenance import make_evidence, record_material_derivation, record_run
from .query import (
    CapabilityMatch,
    assets,
    facilities,
    find_qualified_assets,
    material_lots,
    qualification_rank,
    zones,
)
from .schema import (
    Asset,
    Capability,
    Facility,
    MaterialLot,
    PropertyValue,
    Zone,
    register_extensions,
)
from .validation import (
    InventoryValidationError,
    validate_catalog,
    validate_document,
    validate_inventory_graph,
)

__all__ = [
    "Asset",
    "Capability",
    "CapabilityMatch",
    "Facility",
    "InventoryValidationError",
    "MaterialLot",
    "PropertyValue",
    "Zone",
    "add_all",
    "add_child",
    "assets",
    "configure_namespace",
    "configure_synbiohub",
    "discard",
    "discard_implementation",
    "facilities",
    "find_qualified_assets",
    "grid_positions",
    "locate",
    "make_asset",
    "make_bacterial_stock",
    "make_box",
    "make_capability",
    "make_diluted_plasmid",
    "make_document",
    "make_evidence",
    "make_facility",
    "make_fridge_4c",
    "make_fridge_minus20",
    "make_fridge_minus80",
    "make_material_lot",
    "make_plated_strain",
    "make_procured_material",
    "make_property",
    "make_shelf",
    "make_single_well_petri_dish_plate",
    "make_solid_96_well_plate",
    "make_solid_media_plate",
    "make_square_96_position_plate",
    "make_zone",
    "material_lots",
    "move_item",
    "place_in_container",
    "place_in_plate",
    "place_item",
    "qualification_rank",
    "read_document",
    "record_material_derivation",
    "record_run",
    "register_extensions",
    "remove_from_container",
    "validate_catalog",
    "validate_document",
    "validate_inventory_graph",
    "write_document",
    "write_rdfxml",
    "write_turtle",
    "zones",
]

# Vocabulary constants are part of the top-level API without relying on a
# wildcard import internally. This keeps the vocabulary extensible and makes
# ``from sbol_inventory import ROOM`` work as before.
for _name in _namespaces.__all__:
    globals()[_name] = getattr(_namespaces, _name)
__all__ += _namespaces.__all__

del _name
