"""Stable rule identifiers for SBOLInventory Profile 0.2."""

SBOL_CORE_RULE = "sbolinv-10001"
BASE_TYPE_RULE = "sbolinv-10002"
EXTENSION_PRESERVATION_RULE = "sbolinv-10003"
PROPERTY_RANGE_RULE = "sbolinv-10004"

ZONE_FACILITY_RULE = "sbolinv-12001"
ZONE_KIND_RULE = "sbolinv-12002"
ZONE_ACTIVE_RULE = "sbolinv-12003"
ZONE_PARENT_RULE = "sbolinv-12004"
ZONE_CYCLE_RULE = "sbolinv-12005"
ZONE_POLICY_RULE = "sbolinv-12006"
ZONE_CONDITION_KIND_RULE = "sbolinv-12007"

ASSET_FACILITY_RULE = "sbolinv-13001"
ASSET_KIND_RULE = "sbolinv-13002"
ASSET_ACTIVE_RULE = "sbolinv-13003"
ASSET_PART_OF_RULE = "sbolinv-13004"
ASSET_ESTABLISHES_ZONE_RULE = "sbolinv-13005"
ASSET_ALLOWED_POSITION_RULE = "sbolinv-13006"
ASSET_CONTAINMENT_CYCLE_RULE = "sbolinv-13007"
ASSET_CAPABILITY_KIND_RULE = "sbolinv-13008"

LOCATION_FACILITY_RULE = "sbolinv-13501"
LOCATION_POSITION_RULE = "sbolinv-13502"
LOCATION_OCCUPANCY_RULE = "sbolinv-13503"

CAPABILITY_OWNER_RULE = "sbolinv-14001"
CAPABILITY_KIND_RULE = "sbolinv-14002"
CAPABILITY_QUALIFICATION_RULE = "sbolinv-14003"
CAPABILITY_CONTROL_MODE_RULE = "sbolinv-14004"
CAPABILITY_ACTIVE_RULE = "sbolinv-14005"
CAPABILITY_PARAMETER_KIND_RULE = "sbolinv-14006"

PROPERTY_OWNER_RULE = "sbolinv-15001"
PROPERTY_KIND_RULE = "sbolinv-15002"
PROPERTY_VALUE_RULE = "sbolinv-15003"
PROPERTY_IRI_RULE = "sbolinv-15004"
PROPERTY_UNIT_RULE = "sbolinv-15005"

MATERIAL_BASE_TYPE_RULE = "sbolinv-16001"
MATERIAL_KIND_RULE = "sbolinv-16002"
MATERIAL_FACILITY_RULE = "sbolinv-16003"
MATERIAL_BUILT_RULE = "sbolinv-16004"
MATERIAL_ACTIVE_RULE = "sbolinv-16005"
MATERIAL_LINEAGE_RULE = "sbolinv-16006"

RUN_ASSET_RULE = "sbolinv-17001"
RUN_INPUT_MATERIAL_RULE = "sbolinv-17002"
RUN_REQUIRES_ASSET_RULE = "sbolinv-17003"

QUERY_QUALIFICATION_RULE = "sbolinv-18001"
QUERY_ELIGIBILITY_RULE = "sbolinv-18002"
QUERY_ORDER_RULE = "sbolinv-18003"

VALIDATOR_RULE_IDS = frozenset(
    {
        SBOL_CORE_RULE,
        BASE_TYPE_RULE,
        PROPERTY_RANGE_RULE,
        ZONE_FACILITY_RULE,
        ZONE_KIND_RULE,
        ZONE_ACTIVE_RULE,
        ZONE_PARENT_RULE,
        ZONE_CYCLE_RULE,
        ZONE_POLICY_RULE,
        ZONE_CONDITION_KIND_RULE,
        ASSET_FACILITY_RULE,
        ASSET_KIND_RULE,
        ASSET_ACTIVE_RULE,
        ASSET_PART_OF_RULE,
        ASSET_ESTABLISHES_ZONE_RULE,
        ASSET_ALLOWED_POSITION_RULE,
        ASSET_CONTAINMENT_CYCLE_RULE,
        ASSET_CAPABILITY_KIND_RULE,
        LOCATION_FACILITY_RULE,
        LOCATION_POSITION_RULE,
        LOCATION_OCCUPANCY_RULE,
        CAPABILITY_OWNER_RULE,
        CAPABILITY_KIND_RULE,
        CAPABILITY_QUALIFICATION_RULE,
        CAPABILITY_CONTROL_MODE_RULE,
        CAPABILITY_ACTIVE_RULE,
        CAPABILITY_PARAMETER_KIND_RULE,
        PROPERTY_OWNER_RULE,
        PROPERTY_KIND_RULE,
        PROPERTY_VALUE_RULE,
        PROPERTY_IRI_RULE,
        PROPERTY_UNIT_RULE,
        MATERIAL_BASE_TYPE_RULE,
        MATERIAL_KIND_RULE,
        MATERIAL_FACILITY_RULE,
        MATERIAL_BUILT_RULE,
        MATERIAL_ACTIVE_RULE,
        MATERIAL_LINEAGE_RULE,
        RUN_ASSET_RULE,
        RUN_INPUT_MATERIAL_RULE,
        RUN_REQUIRES_ASSET_RULE,
    }
)

QUERY_RULE_IDS = frozenset(
    {
        QUERY_QUALIFICATION_RULE,
        QUERY_ELIGIBILITY_RULE,
        QUERY_ORDER_RULE,
    }
)

RULE_IDS = VALIDATOR_RULE_IDS | QUERY_RULE_IDS | {EXTENSION_PRESERVATION_RULE}

__all__ = [
    name
    for name, value in globals().copy().items()
    if (name.endswith("_RULE") and isinstance(value, str)) or name.endswith("_RULE_IDS")
] + ["RULE_IDS"]
