[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "SBOLInventory"
version = "0.1.0"
description = "Python package for SBOL-based laboratory inventory management."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "sbol2",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "jupyter",
    "ipykernel",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
